apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: davt
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: "https://{{ HOSTNAME }}/auth?capability=read:workspace"
    # This _could_ work if we upgrade the ingress controller
    # nginx.ingress.kubernetes.io/auth-snippet: |
    #   set $capability_operation "";
    #   if ( $request_method ~ ^(HEAD|GET|OPTIONS|PROPFIND)$ ) {
    #       set $capability_operation "read";
    #   }
    #   if ( $request_method ~ ^(POST|PUT|PATCH|DELETE|PROPPATCH|MKCOL|COPY|MOVE)$ ) {
    #       set $capability_operation "write";
    #   }

    nginx.ingress.kubernetes.io/auth-sign-in: "https://{{ HOSTNAME }}/oauth2/sign_in"
    nginx.ingress.kubernetes.io/auth-request-redirect: "$request_uri"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      error_page 403 = "https://{{ HOSTNAME }}/oauth2/start?rd=$request_uri";

spec:
  rules:
  - host: {{ HOSTNAME }}
    http:
      paths:
{% for mount, mount_export in MOUNTS.items() %}
      - path: /api/dav{{ mount_export }}
        backend:
          serviceName: davt
          servicePort: 80
{% endfor %}
