apiVersion: apps/v1
kind: Deployment
metadata:
  name: davt-deployment
  labels:
    app: davt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: davt
  template:
    metadata:
      labels:
        app: davt
    spec:
      containers:
      - name: davt
        image: lsstdm/davt
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: davt-nginx-config-volume
          mountPath: "/etc/nginx/nginx.conf"
          subPath: nginx.conf
          readOnly: true
        - name: davt-datasets-volume
          mountPath: "/datasets"
          readOnly: true
        - mountPath: /cache
          name: cache-volume
      volumes:
      - name: davt-nginx-config-volume
        configMap:
          name: davt-nginx-config
      - name: davt-datasets-volume
        persistentVolumeClaim:
          claimName: datasets-lsst-pdac
      - name: cache-volume
        emptyDir: {}

---

kind: Service
apiVersion: v1
metadata:
  name: davt-service
spec:
  selector:
    app: davt
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: "https://lsst-lsp-int.ncsa.illinois.edu/auth?capability=read:workspace"
    # This _could_ work if we upgrade the ingress controller
    # nginx.ingress.kubernetes.io/auth-snippet: |
    #   set $capability_operation "";
    #   if ( $request_method ~ ^(HEAD|GET|OPTIONS|PROPFIND)$ ) {
    #       set $capability_operation "read";
    #   }
    #   if ( $request_method ~ ^(POST|PUT|PATCH|DELETE|PROPPATCH|MKCOL|COPY|MOVE)$ ) {
    #       set $capability_operation "write";
    #   }

    nginx.ingress.kubernetes.io/auth-sign-in: "https://lsst-lsp-int.ncsa.illinois.edu/oauth2/sign_in"
    nginx.ingress.kubernetes.io/auth-request-redirect: "$request_uri"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      error_page 403 = "https://lsst-lsp-int.ncsa.illinois.edu/oauth2/start?rd=$request_uri";

  name: davt-ingress
spec:
  rules:
  - host: lsst-lsp-int.ncsa.illinois.edu
    http:
      paths:
      - path: /workspace
        backend:
          serviceName: davt-service
          servicePort: 80
  tls:
  - hosts:
    - lsst-lsp-int.ncsa.illinois.edu
    secretName: tls-certificate-lsp-int
