apiVersion: v1
kind: PersistentVolume
metadata:
  name: davt-datasets-volume
  annotations:
    volume.beta.kubernetes.io/mount-options: local_lock=all
spec:
  accessModes:
  - ReadOnlyMany
  capacity:
    storage: 1100Ti
  nfs:
    path: /lsst/datasets
    server: lsst-nfs.ncsa.illinois.edu
  persistentVolumeReclaimPolicy: Retain

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: davt-datasets-claim
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1090Ti
  volumeName: davt-datasets-volume


